### ISSUE TITLE
Does not start the apache server, only mysql.

### ISSUE THREAD

**Issue by supermoos** [tonyspiro/gulp-mamp#6] opened 2016-07-26 11:25 UTC
With Mamp 3.5 it does not seem to work. The apache instance is never started, the mysql instance is though.

**Comment by stalinkay** [comment] 2016-08-04 19:59
+1

**Comment by stalinkay** [comment] 2016-08-04 20:17
@tonyspiro @supermoos the issue is caused by a missing mod_example.so and possibly some php versions and results in the following error:

```
httpd: Syntax error on line 83 of /Applications/MAMP/conf/apache/httpd.conf: Cannot load /Applications/MAMP/Library/modules/mod_example.so into server: dlopen(/Applications/MAMP/Library/modules/mod_example.so, 10): image not found
```

mod_example.so does not ship with the current version of mamp as such it should not be included in the http.conf.template

`/Applications/MAMP/conf/apache/httpd.conf` of a clean mamp install works perfectly

`/Applications/MAMP/conf/apache/original/httpd.conf` contains mod_example.so so this is also flawed.

I think the gulp-mmap template should be using the clean file from mamp 3.5, I don't know if that is backward compatible.

[httpd_gulp_mamp_0.0.4.conf.txt](https://github.com/tonyspiro/gulp-mamp/files/402595/httpd_gulp_mamp_0.0.4.conf.txt)
[httpd_mamp_3.5.conf.txt](https://github.com/tonyspiro/gulp-mamp/files/402596/httpd_mamp_3.5.conf.txt)

**Comment by tonyspiro** [comment] 2016-08-04 20:19
Please open up a PR and I'll merge.

**Comment by stalinkay** [comment] 2016-08-04 20:20
Cool.

**Comment by stalinkay** [comment] 2016-08-04 21:45
@tonyspiro, It seems this issue was already resolved with #4 on github. Yet installing it via npm install gulp-mamp results in an outdated file with the following lines:

```
LoadModule example_module modules/mod_example.so
```

```
LoadModule php5_module        /Applications/MAMP/bin/php/php5.6.2/modules/libphp5.so
```

Compared to the following on github:

```
LoadModule php5_module        /Applications/MAMP/bin/php/php5.6.10/modules/libphp5.so
```

Try bumping the version and publishing it again.

The file below works fine. I can't make a pull request because it exactly the same file. No change to commit.

[httpd.conf-template.txt](https://github.com/tonyspiro/gulp-mamp/files/402772/httpd.conf-template.txt)

**Comment by tonyspiro** [comment] 2016-08-07 02:42
@stalinkay The newest version has been published to npm.  Let me know if you have any issues.

**Closed as completed by tonyspiro** 2016-08-07 02:42 UTC

**Comment by stalinkay** [comment] 2016-08-28 13:53
@tonyspiro All is well. Thanks.
